# Generated by Django 5.0.4 on 2024-05-09 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_alter_post_cat_alter_post_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='cat',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='posts', to='post.category', verbose_name='Категория'),
            preserve_default=False,
        ),
    ]
