# Generated by Django 5.0.4 on 2024-06-01 10:54

import easy_thumbnails.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_alter_category_cat_title_alter_category_slug_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created'], 'verbose_name': 'Комментарий', 'verbose_name_plural': 'Комментарии'},
        ),
        migrations.AlterField(
            model_name='post',
            name='title_image',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, null=True, upload_to='post/%Y/%m/%d/', verbose_name='Превью'),
        ),
        migrations.DeleteModel(
            name='PostImage',
        ),
    ]
