from django.urls import path
from django.views.decorators.cache import cache_page

from . import views

urlpatterns = [
    path('',
         views.PostListView.as_view(),
         name='index'),
    path('category/<slug:slug>/',
         views.CategoryListView.as_view(),
         name='category_list'),
    path('<int:day>/<int:month>/<int:year>/<slug:slug>',
         views.PostDetailView.as_view(),
         name='post_detail'),
    path('about/',
         views.AboutView.as_view(),
         name='about'),
    path('contacts/',
         views.ContactsView.as_view(),
         name='contacts'),
    path('<int:post_id>/comment',
         views.PostCommentView.as_view(),
         name='post_comment'),
    path('create_post/',
         views.PostCreateView.as_view(),
         name='create_post'),
    path('edit/<slug:slug>/',
         views.PostUpdateView.as_view(),
         name='edit_page'),
    path('delete/<slug:slug>/',
         views.PostDeleteView.as_view(),
         name='delete_post'),
    path('edit_comment/<int:pk>/',
         views.CommentUpdateView.as_view(),
         name='edit_comment'),
    path('delete_comment/<int:pk>/',
         views.CommentDeleteView.as_view(),
         name='delete_comment'),
    path('tag/<str:tag_slug>/',
         (views.PostListByTagView.as_view()),
         name='post_list_tag'),
    path('search/',
         views.post_search,
         name='post_search'),
    path('following/',
         (views.PostListByFollowingView.as_view()),
         name='following_list'),
]
