# Generated by Django 5.0.4 on 2024-06-01 11:46

import easy_thumbnails.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_user_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, default='account/default.png', null=True, upload_to='account/%Y/%m/%d/', verbose_name='Изображение'),
        ),
    ]
